import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [isLoading, setIsLoading] = useState(false)
  const [image, setImage] = useState(null)
  const [uploadedImageURL, setuploadedImageURL] = useState(null)
  const [liveURL, setLiveURL] = useState(null)

  const handleOnChange = (event) => {
    if (event.target.files && event.target.files[0]) {
      const i = event.target.files[0]
      setImage(i)
      setuploadedImageURL(URL.createObjectURL(i))
    }
  }

  const handleOnSubmit = async (event) => {
    event.preventDefault()
    setIsLoading(true)

    const formData = new FormData()
    formData.append('file', image)
    formData.append('upload_preset', process.env.NEXT_PUBLIC_CLOUDINARY_PRESET_NAME)

    const response = await fetch(`https://api.cloudinary.com/v1_1/${process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}/image/upload`, {
      method: 'POST',
      body: formData
    }).then(r => r.json())
    
    console.log(response)
    setLiveURL(response.secure_url)
    setIsLoading(false)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Image Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoading &&
        <main className={styles.main}>
          Loading
        </main>
      }

      {!isLoading &&


        <main className={styles.main}>
          {liveURL && 
            <div>
              <a href={liveURL}>View the uploaded image</a>
            </div>
          }

          {uploadedImageURL &&
            <div>
              <Image
                src={uploadedImageURL}
                alt="Unable to load image"
                width={720}
                height={720}
              />
            </div>
          }

          <form method='POST' onSubmit={handleOnSubmit}>
            <h4>Select Image</h4>
            <input type="file" name="file" onChange={handleOnChange} />
            <button type='submit'>Upload</button>
          </form>

          
        </main>
      }

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
